services:
   nk.admin.parametre:
      class: Nk\AdminBundle\Admin\ParametreAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: parametres, label: Parametre }
      arguments: [null, Nk\AdminBundle\Entity\Parametre, SonataAdminBundle:CRUD]
