services:
   nk.admin.parameter:
      class: Nk\AdminBundle\Admin\ParameterAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: parameters, label: parametre }
      arguments: [null, Nk\AdminBundle\Entity\Parameter, Nk\AdminBundle\Admin\ParameterAdmin]